call npm install --save-dev gulp
call npm install --save-dev gulp-util
call npm install --save-dev gulp-concat
call npm install --save-dev gulp-browserify
call npm install --save-dev gulp-compass
call npm install --save-dev gulp-connect
call npm install --save-dev gulp-if
call npm install --save-dev gulp-uglify
call npm install --save-dev gulp-minify-html
call npm install --save-dev jquery